org: mfpekala
app: cyclicism

service: cyclicism
provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: test_api.app
    packRequirements: false
    port: 3000
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
